#!/usr/bin/env python3
"""GravPool bundle — one command to go from zero to OpenAI-compatible endpoint.

Does three things, in order:
  1. Login an Antigravity account (browser consent -> auth file).
  2. Download the matching CLIProxyAPI binary for this OS/arch (the layer that
     exposes an OpenAI-compatible /v1 endpoint in front of the auth files).
  3. Write a ready-to-run `config.yaml` pointing at the auth dir.

Run:
    python bundle.py            # interactive: login + fetch proxy + config
    python bundle.py --no-login # skip login, just fetch proxy + config
    python bundle.py --no-proxy # login only, skip downloading CLIProxyAPI

Stdlib only. Requires Python 3.9+.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import zipfile

GITHUB_API = "https://api.github.com/repos/router-for-me/CLIProxyAPI/releases/latest"
AUTH_DIR = "auth"
BIN_DIR = "bin"
CONFIG_PATH = "config.yaml"
PROXY_PORT = 8317
API_KEY = "sk-local"


def _sys() -> tuple[str, str]:
    """Return (os_key, arch_key) matching CLIProxyAPI asset names."""
    system = platform.system().lower()
    machine = platform.machine().lower()
    os_key = {"windows": "windows", "darwin": "darwin", "linux": "linux"}.get(system)
    if not os_key:
        raise RuntimeError(f"unsupported OS: {system}")
    arch_key = "aarch64" if machine in ("aarch64", "arm64") else "amd64"
    return os_key, arch_key


def _asset_url(os_key: str, arch_key: str) -> str:
    """Find the release asset matching os/arch, returning its download URL."""
    with urllib.request.urlopen(GITHUB_API, timeout=30) as resp:
        rel = json.loads(resp.read().decode())
    tag = rel["tag_name"]
    assets = rel.get("assets", [])
    if not assets:
        # some releases use tarball/zipball instead of per-asset binaries
        raise RuntimeError(f"release {tag} has no assets")
    want = f"{os_key}_{arch_key}"
    # prefer no-plugin variant only as fallback; plain variant first
    candidates = [a for a in assets if want in a["name"]]
    if not candidates:
        raise RuntimeError(f"no asset for {want} in release {tag}")
    candidates.sort(key=lambda a: "no-plugin" in a["name"])  # plain first
    return candidates[0]["browser_download_url"]


def _download(url: str, dest: str) -> None:
    print(f"  downloading {url.split('/')[-1]} ...")
    req = urllib.request.Request(url, headers={"User-Agent": "gravpool-bundle"})
    with urllib.request.urlopen(req, timeout=300) as resp, open(dest, "wb") as f:
        shutil.copyfileobj(resp, f)


def _extract(archive: str, dest_dir: str) -> None:
    os.makedirs(dest_dir, exist_ok=True)
    if archive.endswith(".zip"):
        with zipfile.ZipFile(archive) as z:
            z.extractall(dest_dir)
    else:
        with tarfile.open(archive) as t:
            # Prevent path traversal
            for member in t.getmembers():
                if member.name.startswith("/") or ".." in member.name:
                    continue
                t.extract(member, dest_dir)
    os.remove(archive)
    
    # Ensure binary is executable
    exe = "cli-proxy-api.exe" if platform.system().lower() == "windows" else "cli-proxy-api"
    bin_path = os.path.join(dest_dir, exe)
    if os.path.exists(bin_path):
        os.chmod(bin_path, 0o755)


def fetch_proxy() -> None:
    """Download + extract CLIProxyAPI binary into BIN_DIR."""
    os_key, arch_key = _sys()
    url = _asset_url(os_key, arch_key)
    ext = ".zip" if os_key == "windows" else ".tar.gz"
    tmp = os.path.join(tempfile.gettempdir(), f"cliproxyapi_{os_key}{ext}")
    _download(url, tmp)
    _extract(tmp, BIN_DIR)
    print(f"  proxy ready in {BIN_DIR}/")


def write_config() -> None:
    """Write config.yaml pointing the proxy at AUTH_DIR."""
    cfg = (
        "# Generated by GravPool bundle. Edit access.api-keys as you like.\n"
        f"server:\n"
        f"  host: 127.0.0.1\n"
        f"  port: {PROXY_PORT}\n"
        f"oauth:\n"
        f"  auth-dir: ./{AUTH_DIR}\n"
        f"access:\n"
        f"  api-keys:\n"
        f'    - "{API_KEY}"\n'
    )
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(cfg)
    print(f"  wrote {CONFIG_PATH}")


def login() -> None:
    """Run GravPool's add-account flow."""
    print("  login akun (browser consent) ...")
    subprocess.run(
        [sys.executable, "-m", "gravpool.cli", "add-account", "--auth-dir", AUTH_DIR],
        check=False,
    )


def _proxy_cmd() -> str:
    exe = "cli-proxy-api.exe" if platform.system().lower() == "windows" else "cli-proxy-api"
    return os.path.join(BIN_DIR, exe)


def main() -> int:
    p = argparse.ArgumentParser(description="GravPool one-command bundle")
    p.add_argument("--no-login", action="store_true", help="skip login, only fetch proxy + config")
    p.add_argument("--no-proxy", action="store_true", help="skip proxy download, only login")
    args = p.parse_args()

    print("== GravPool bundle ==")
    if not args.no_login:
        login()
    else:
        print("  (login skipped)")

    if not args.no_proxy:
        fetch_proxy()
    else:
        print("  (proxy download skipped)")

    write_config()

    print()
    print("== Done. Next steps ==")
    if not args.no_login:
        print(f"  Login Account : python -m gravpool.cli add-account --auth-dir {AUTH_DIR}")
    print(f"  Start GravPool: python -m gravpool.cli gui --auth-dirs {AUTH_DIR}")
    print(f"  (Dashboard at http://127.0.0.1:8390)")
    print(f"  (API at       http://127.0.0.1:8390/v1)")
    print(f"  API key       : {API_KEY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
